spring:
  application:
    name: payr-orders-api
  kafka:
    bootstrap-servers: 'broker:29092'

payr:
  kafka:
    topic-orders-new: orders.new
    topic-orders-error: orders.error
    topic-notification: notification.new